"""Created the CertificateField model

Revision ID: 1397907e9544
Revises: c6e6bb0a60ed
Create Date: 2024-06-20 16:39:22.024360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1397907e9544'
down_revision = 'c6e6bb0a60ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate', sa.Integer(), nullable=True),
    sa.Column('certificate_type_field', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['certificate'], ['certificate.id'], ),
    sa.ForeignKeyConstraint(['certificate_type_field'], ['certificate_type_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_field')
    # ### end Alembic commands ###
