"""	oken is now the primary key of the Recipient model

Revision ID: 4ed30a298862
Revises: 624946fc5c9d
Create Date: 2024-07-01 15:27:18.100679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed30a298862'
down_revision = '624946fc5c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)

    # ### end Alembic commands ###
