"""Added a 	oken field in the Recipient model

Revision ID: 624946fc5c9d
Revises: c5d469d2a600
Create Date: 2024-07-01 13:55:41.498544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624946fc5c9d'
down_revision = 'c5d469d2a600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=13), nullable=True))
        batch_op.alter_column('certificate_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('certificate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('token')

    # ### end Alembic commands ###
