"""Added a 

Revision ID: 99c5f0446b0b
Revises: d4c603ef0977
Create Date: 2024-06-25 12:04:33.949887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c5f0446b0b'
down_revision = 'd4c603ef0977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_type_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_type_field', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
