"""Created the CertificateType and CertificateTypeField models

Revision ID: bd1ad8cff219
Revises: fbedc734aace
Create Date: 2024-05-24 13:21:59.321134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ad8cff219'
down_revision = 'fbedc734aace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_type_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.Enum('text', 'date', name='fieldvaluetypeenum'), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_type'], ['certificate_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_type_field')
    op.drop_table('certificate_type')
    # ### end Alembic commands ###
