"""Created the Certificate model

Revision ID: c6e6bb0a60ed
Revises: 7d3d43853b73
Create Date: 2024-06-20 14:13:03.266753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e6bb0a60ed'
down_revision = '7d3d43853b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('issuance_date', sa.Date(), nullable=True),
    sa.Column('issuance_locale', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    # ### end Alembic commands ###
